### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by emedchill** [paypal/Payouts-PHP-SDK#10]
I am trying to update my SDK from v1 to v2 (this repo) because it is deprecated but according to packagist this package is also abandoned (and paypal/paypalhttp, which this repo uses). What's going on?

https://packagist.org/packages/paypal/paypal-payouts-sdk

**Comment by aninja8** [comment]
@emedchill This SDK is not abandoned. It is fixed.

**Comment by emedchill** [comment]
Could you also fix packagist? It is still saying it is abandoned. https://packagist.org/packages/paypal/paypal-payouts-sdk

**Comment by aninja8** [comment]
@emedchill Thanks for bringing it to my notice. I am working on figuring out why this keeps switching to abandoned. Reopening this for now
