### ISSUE TITLE
How to use this SDK for live paypal payout API

### ISSUE THREAD

**Issue by vmebackendapi** [paypal/Payouts-PHP-SDK#22]
Hello,

This is working fine for Sandbox Environment. Now we want to use for Live Enviorment. so if we are replacing SandboxEnvironment with LiveEnvironment then we are not able to find this service class LiveEnvironment. so have to add this class manually on our side?

Thanks!

**Comment by barduck007** [comment]
There is no LiveEnvironment class. The one you are searching is ProductionEnvironment I guess.

https://github.com/paypal/Payouts-PHP-SDK/blob/master/lib/PaypalPayoutsSDK/Core/ProductionEnvironment.php

**Comment by vmebackendapi** [comment]
Hello,

Ok. Thanks. as it was mentioned use LiveEnvironment class somewhere. so i was looking into it.
