### ISSUE TITLE
Error braintreehttp

### ISSUE THREAD

**Issue by Gabrielrz** [paypal/Payouts-PHP-SDK#6]
me ha salido este error al intentar usar el ejemplo de pago CreatePayoutSample.php

Fatal error: Uncaught TypeError: Argument 1 passed to BraintreeHttp\HttpClient::execute() must be an instance of BraintreeHttp\HttpRequest, instance of PaypalPayoutsSDK\Payouts\PayoutsPostRequest given, called in C:\wamp64\www\pruebasPaypal\pagos.php on line 40 and defined in C:\wamp64\www\pruebasPaypal\vendor\braintree\braintreehttp\lib\BraintreeHttp\HttpClient.php on line 58

cuando utilizo el codigo de ejemplo de los pasos de la pagina principal si que funciona pero no se si es la manera mas correcta

// Creating an environment
$clientId = "<<PAYPAL-CLIENT-ID>>";
$clientSecret = "<<PAYPAL-CLIENT-SECRET>>";

$environment = new SandboxEnvironment($clientId, $clientSecret);
$client = new PayPalHttpClient($environment);
utilizo esto en lugar de:
 $client = new PayPalHttpClient($environment);

**Comment by aninja8** [comment]
Please uninstall the older version of the PayPal SDK from your system.

**Comment by Gabrielrz** [comment]
gracias, tuve que actualizar las dependencias de composer del proyecto para que se desintale braintree
