### ISSUE TITLE
where is PayPalHttp\  , can not find name space PayPalHttp

### ISSUE THREAD

**Issue by weizewei** [paypal/Payouts-PHP-SDK#8]
![image](https://user-images.githubusercontent.com/27813629/87518598-0dba9a00-c6b3-11ea-924d-7a72eef971a5.png)

**Comment by aninja8** [comment]
Hi @weizewei 

Please try running `composer install`.

If you are facing further issues please post an issue on https://github.com/paypal/Checkout-PHP-SDK

**Comment by weizewei** [comment]
thanks  , it solved
