### ISSUE TITLE
abandonned?

### ISSUE THREAD

**Issue by jlbrs** [paypal/Payouts-PHP-SDK#9]
is it normal that this package is still advertised on paypal sdk documentation, and Composer finds it abandonned? 

```
Package paypal/paypal-payouts-sdk is abandoned, you should avoid using it. No replacement was suggested.
Package paypal/paypalhttp is abandoned, you should avoid using it. No replacement was suggested.
```

thank you!

**Comment by Braunson** [comment]
Also curious, as Packagist is saying this package is abandoned, but I see updates as recent as March? Can we expect more updates?

**Comment by aninja8** [comment]
This has been unabandoned. @jlbrs @Braunson
